image: node:10

cache:
  paths:
  - node_modules/

stages:
  - test

before_script:
  - rm -R ~/.node-gyp
  - npm install -g node-gyp
  - npm install
  - node-gyp configure

test_sockets:
  stage: test
  script:
   - node-gyp build .
   - npm test