image: node:10

cache:
  paths:
  - node_modules/

stages:
  - test

before_script:
  - npm install -g node-gyp
  - npm install
  - node-gyp configure

test_sockets:
  stage: test
  script:
   - node-gyp build .
   - ls -R build
   - cd build; make
   - ls -R build
   - npm test