image: node:12.1.0

cache:
  paths:
  - node_modules/

stages:
  - test


before_script:
  - npm install -g node-gyp

test_sockets:
  stage: test
  script:
   - npm install
   - npm build .
   - npm test