image: node:12.1.0

cache:
  paths:
  - node_modules/

stages:
  - test


before_script:
  - npm install -g node-gyp
  - node-gyp configure

test_sockets:
  stage: test
  script:
   - npm install
   - node-gyp build .
   - npm test